name: dev

on:
  push:
    branches:
      - dev
      - feature/*

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Print tag
        run: git describe --tags
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
      - name: Pre-build
        run: echo "${{ secrets.LOCAL_PROPERTIES }}" >> ./local.properties
      - name: Build debug APK
        run: ./gradlew assembleDebug
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Debug APK
          path: app/build/outputs/apk/debug/*.apk
          